### ISSUE TITLE
So it's working perfectly but what if I don't have the right port then it won't return any result right ?

### ISSUE THREAD

**Issue by abdelrhmanshokr** [minomy13/server-reachability#2]

**Comment by minomy13** [comment]
Sorry for the late answer. It will return `false` after 1 minute and 20 seconds. Should I implement a function to set a shorter timeout?

**Comment by minomy13** [comment]
I have done it. Please see the code example in the README. Please tell me if this works for you. :)

**Comment by minomy13** [comment]
I closed the issue now. Please reopen if it does not work.
